"""Markdown report writer."""

from pathlib import Path
from typing import Dict, Any

from .base import BaseReporter
from ...pipelines.languagemodel import ReportData, EvaluationResult


class MarkdownReporter(BaseReporter):
    """Writes reports in Markdown (MD) format."""

    format_name = "markdown"
    file_extension = ".md"

    def write(self, report_data: ReportData, output_path: Path) -> None:
        """Write report data as Markdown file.

        Args:
            report_data: The report data to write
            output_path: Path to the output file / directory
        """
        markdown = self._generate_markdown(report_data)
        with open(output_path, "w") as f:
            f.write(markdown)

    def _generate_markdown(self, report_data: ReportData) -> str:
        """Generate complete Markdown report."""
        summary = report_data.summary
        config = report_data.configuration

        md = f"""# AVISE Security Report

## Security Evaluation Test Information

| Field | Value |
|-------|-------|
| SET Name | {report_data.set_name} |
| Timestamp | {report_data.timestamp} |
| Duration | {report_data.execution_time_seconds}s |
| ELM Evaluation | {"Yes" if config.get("elm_evaluation_used") else "No"} |

## Summary

| Metric | Count | Rate |
|--------|-------|------|
| Total SETs | {summary["total_sets"]} | - |
| Passed | {summary["passed"]} | {summary["pass_rate"]}% |
| Failed | {summary["failed"]} | {summary["fail_rate"]}% |
| Inconclusive | {summary["error"]} | - |

---

## Results

"""
        md += self._get_results(report_data.results)
        if report_data.ai_summary:
            md += self._get_ai_summary(report_data.ai_summary)
        md += "\n*Report generated by AVISE*\n"
        return md

    def _get_ai_summary(self, ai_summary: Dict[str, Any]) -> str:
        """Generate AI summary section for Markdown report."""
        notes_md = "\n".join(f"- {note}" for note in ai_summary.get("notes", []))
        return f"""---

## AI Security Evaluation Summary

### Issue Summary

{ai_summary.get("issue_summary", "")}

### Recommended Remediations

{ai_summary.get("recommended_remediations", "")}

### Notes

{notes_md}
"""

    def _get_results(self, results: list) -> str:
        """Generate list of results."""
        md = ""
        for result in results:
            if isinstance(result, EvaluationResult):
                set_ = {
                    "set_id": result.set_id,
                    "prompt": result.prompt,
                    "response": result.response,
                    "status": result.status,
                    "reason": result.reason,
                    "attack_type": result.metadata.get("attack_type", ""),
                    "description": result.metadata.get("description", ""),
                    "full_conversation": result.metadata.get("full_conversation", []),
                }
                if result.elm_evaluation:
                    set_["elm_evaluation"] = result.elm_evaluation
            else:
                set_ = result
            md += self._get_set_item(set_)
        md += "---\n\n"
        return md

    def _get_set_item(self, set_: Dict[str, Any]) -> str:
        """Generate Markdown for a single SET item."""
        status_indicator = set_["status"].upper()
        set_label = set_.get("attack_type") or set_.get("description") or ""
        if set_label:
            set_label = f" - {set_label}"

        md = f"""#### [{status_indicator}] {set_["set_id"]}{set_label}

"""
        # Check for conversation format (memory test)
        if set_.get("full_conversation"):
            md += "**Conversation:**\n"
            for msg in set_["full_conversation"]:
                role = msg.get("role", "user")
                content = msg.get("content", "")
                md += f"- **{role}:** {content}\n"
            md += "\n"
        else:
            # Standard prompt/response format
            md += f"""**Prompt:**
```
{set_.get("prompt", "")}
```

**Response:**
```
{set_.get("response", "")}
```

"""

        md += f"**Reason:** {set_.get('reason', '')}\n\n"

        if "elm_evaluation" in set_:
            md += f"""**ELM Evaluation:**
> {set_["elm_evaluation"]}

"""
        return md
