target_model:
  connector: "generic-rest-cl"
  type: "continual_learning"
  api_endpoint:
    base:
      url: "" # Base URL of the target API endpoint
      headers:
        X-API-Key: ""
      method: "POST"
      batch_handling: false
      time_out: 1800 # How long to wait for a response from the endpoint(s) in seconds
      prediction_field: "predicted_label" # Name of the field that contains the model's prediction in the API response
      confidence_field: null # Name of the field that contains the prediction's confidence score (if applicable)
      probabilities_field: "top_k_scores" # Name of the field that contains the prediction's different probabilities (if applicable)
    # If the API has different endpoints for training and inference,
    # insert their details here:
    train:
      url: ""
      headers:
        X-API-Key: ""
      method: "POST"
      batch_handling: true # Can the API handle incoming data in batches
    inference:
      url: ""
      headers:
        X-API-Key: ""
      method: "POST"
      batch_handling: false # Can the API handle incoming data in batches
      prediction_field: "predicted_label" # Name of the field that contains the model's prediction in the API response
      confidence_field: null # Name of the field that contains the prediction's confidence score (if applicable)
      probabilities_field: "top_k_scores" # Name of the field that contains the prediction's different probabilities (if applicable)
