target_model:
  connector: "generic-rest-cl"
  type: "continual_learning"
  api_endpoint:
    base:
      url: "<PLACEHOLDER>" # Base URL of the target API endpoint
      headers: null
      method: "POST"
      time_out: 30 # How long to wait for a response from the endpoint(s) in seconds
      prediction_field: null # Name of the field that contains the model's prediction in the API response
      confidence_field: null # Name of the field that contains the prediction's confidence score (if applicable)
      probabilities_field: null # Name of the field that contains the prediction's different probabilities (if applicable)
    # If the API has different endpoints for training and inference,
    # insert their details here:
    train:
      url: null
      headers: null
      method: "POST"
    inference:
      url: null
      headers: null
      method: "POST"
      prediction_field: null # Name of the field that contains the model's prediction in the API response
      confidence_field: null # Name of the field that contains the prediction's confidence score (if applicable)
      probabilities_field: null # Name of the field that contains the prediction's different probabilities (if applicable)
