"""
Connector for Ollama API communication using the ollama library.
"""
import logging
import ollama
from typing import List, Optional

from .base import BaseConnector, Message
from ..registry import connector_registry

logger = logging.getLogger(__name__)


@connector_registry.register("ollama")
class OllamaConnector(BaseConnector):
    """
    Connector for communicating with the Ollama API.

    Used by tests for sending prompts to testable models and collecting their responses.
    Supports both simple generation and generation with system prompts.
    """

    name = "ollama"

    def __init__(
        self,
        model: str,
        base_url: str = "http://localhost:11434",
        api_key: Optional[str] = None
    ):
        """
        Initialize the Ollama connector.

        Args:
            model: Model name for generation (For example: llama3.2:3b)
            base_url: Base URL for Ollama API (For example: http://localhost:11434)
            api_key: Optional API key for authenticated Ollama instances
        """
        self.model = model
        self.base_url = base_url
        self.api_key = api_key

        # Configure client with optional authentication headers
        if api_key:
            self.client = ollama.Client(
                host=base_url,
                headers={"Authorization": f"Bearer {api_key}"}
            )
        else:
            self.client = ollama.Client(host=base_url)

        logger.info(f"  Ollama Connector Initialized")
        logger.info(f"  Base URL: {base_url}")
        logger.info(f"  Model: {model}")
        if api_key:
            logger.info(f"  API Key: {'*' * 8}...{api_key[-4:] if len(api_key) > 4 else '****'}")

    def single_turn(
        self,
        prompt: str,
        temperature: float = 1.0,
        max_tokens: int = 512
    ) -> str:
        """
        Send a single prompt to the LLM and collect a response.

        Args:
            prompt: The test input prompt.
            temperature: Controls the randomness and creativity of the model.
            max_tokens: Maximum response length in tokens.

        Returns:
            The response generated by the target model.

        Raises:
            RuntimeError: If the API call fails.
        """
        try:
            response = self.client.generate(
                model=self.model,
                prompt=prompt,
                options={
                    "temperature": temperature,
                    "num_predict": max_tokens
                }
            )
            return response.response

        except Exception as e:
            logger.error(f"ERROR while generating response from model: {e}")
            raise RuntimeError(f"Failed to generate a response from model due to an error: {e}")

    def single_turn_with_system_prompt(
        self,
        prompt: str,
        system_prompt: str,
        temperature: float = 0.1,
        max_tokens: int = 128
    ) -> str:
        """
        Send a single prompt to the LLM and collect a response.

        Adds additional system prompt to the request, allowing to instruct the model's behavior.
        This method is intended to be used when sending the original test prompt and test output to
        an evaluative language model for analysis.

        Args:
            prompt: The prompt consisting of the original test prompt and the output of the target model.

            system_prompt: Instructions that define the model's behavior, role, or constraints.
                Used to guide what the model should do and how to respond.

            temperature: Controls the randomness and creativity of the model.
                Set to low as default for deterministic responses.

            max_tokens: Maximum number of tokens in the generated response.

        Returns:
            The response generated by the model.

        Raises:
            RuntimeError: If the API call fails.
        """
        try:
            response = self.client.generate(
                model=self.model,
                prompt=prompt,
                system=system_prompt,
                options={
                    "temperature": temperature,
                    "num_predict": max_tokens
                }
            )
            return response.response

        except Exception as e:
            logger.error(f"ERROR while generating response from model: {e}")
            raise RuntimeError(f"Failed to generate a response from model due to an error: {e}")

    def multi_turn(
        self,
        messages: List[Message],
        temperature: float = 1.0,
        max_tokens: int = 512
    ) -> str:
        """
        Send multi-turn prompts, collect conversation history, and send it back to the stateless API backend.

        Args:
            messages: List of Message objects representing the conversation history.
                Message objects contain 'role' and 'content' attributes.
            temperature: Controls the randomness and creativity of the model.
            max_tokens: Maximum response length in tokens.

        Returns:
            The model's response for the latest turn.

        Raises:
            RuntimeError: If the API call fails.
        """
        try:
            # Convert Message objects to Ollama's expected format
            ollama_messages = [
                {"role": msg.role, "content": msg.content}
                for msg in messages
            ]

            response = self.client.chat(
                model=self.model,
                messages=ollama_messages,
                options={
                    "temperature": temperature,
                    "num_predict": max_tokens
                }
            )
            return response["message"]["content"]

        except Exception as e:
            logger.error(f"ERROR during chat with model: {e}")
            raise RuntimeError(f"Failed to chat with model: {e}")

    def _match_model(self, model_name: str, available_models: List[str]) -> bool:
        """Check if a model name exists in the list of available models."""
        for model in available_models:
            if model_name == model:
                return True
        return False

    def health_check(self) -> bool:
        """
        Check if the connector can reach the Ollama backend and the target model is available.

        Returns:
            True if backend is reachable and the target model exists.

        Raises:
            ConnectionError: If the backend is not reachable.
            ValueError: If the model is not found.
        """
        # Step 1: Check backend connectivity and get available models
        try:
            model_names = self.list_models()
        except Exception as e:
            raise ConnectionError(f"Cannot connect to Ollama backend at {self.base_url}: {e}")

        # Step 2: Check if model exists
        logger.info(f"Available models found: {model_names}")

        if self._match_model(self.model, model_names):
            logger.info(f"Model '{self.model}' found.")
            return True

        raise ValueError(
            f"Model '{self.model}' not found in Ollama backend. "
            f"Available models: {model_names}"
        )

    def list_models(self) -> List[str]:
        """
        Helper function, used by health_check() to verify model availability.

        Returns:
            List of model names.

        Raises:
            Exception: If the backend is not reachable.
        """
        response = self.client.list()
        models_list = response.get('models', [])

        model_names = []
        for model in models_list:
            name = model.get("model")
            if name:
                model_names.append(name)

        return model_names
