"""
Markdown report writer.
"""
from pathlib import Path
from typing import Dict, Any

from .base import BaseReporter
from ...pipelines.base import ReportData, AnalysisResult


class MarkdownReporter(BaseReporter):
    """
    Writes reports in Markdown (MD) format.
    
    """

    format_name = "markdown"
    file_extension = ".md"

    def write(self, report_data: ReportData, output_path: Path) -> None:
        """
        Write report data as Markdown file.

        Args:
            report_data: The report data to write
            output_path: Path to the output file / directory
        """
        markdown = self._generate_markdown(report_data)
        with open(output_path, 'w') as f:
            f.write(markdown)

    def _generate_markdown(self, report_data: ReportData) -> str:
        """Generate complete Markdown report."""
        summary = report_data.summary
        config = report_data.configuration

        md = f"""# AIVuT Security Report

## Test Information

| Field | Value |
|-------|-------|
| Test Name | {report_data.test_name} |
| Timestamp | {report_data.timestamp} |
| Duration | {report_data.execution_time_seconds}s |
| ELM Evaluation | {'Yes' if config.get('elm_evaluation_used') else 'No'} |

## Summary

| Metric | Count | Rate |
|--------|-------|------|
| Total Tests | {summary['total_tests']} | - |
| Passed | {summary['passed']} | {summary['pass_rate']}% |
| Failed | {summary['failed']} | {summary['fail_rate']}% |
| Inconclusive | {summary['error']} | - |

---

## Results

"""
        md += self._get_results(report_data.results)
        md += "\n*Report generated by AIVuT Framework*\n"
        return md

    def _get_results(self, results: list) -> str:
        """Generate list of results."""
        md = ""
        for result in results:
            if isinstance(result, AnalysisResult):
                test = {
                    "test_id": result.test_id,
                    "prompt": result.prompt,
                    "response": result.response,
                    "status": result.status,
                    "reason": result.reason,
                    "attack_type": result.metadata.get("attack_type", ""),
                    "description": result.metadata.get("description", ""),
                    "full_conversation": result.metadata.get("full_conversation", [])
                }
                if result.elm_evaluation:
                    test["elm_evaluation"] = result.elm_evaluation
            else:
                test = result
            md += self._get_test_item(test)
        md += "---\n\n"
        return md

    def _get_test_item(self, test: Dict[str, Any]) -> str:
        """Generate Markdown for a single test item."""
        status_indicator = test['status'].upper()
        test_label = test.get("attack_type") or test.get("description") or ""
        if test_label:
            test_label = f" - {test_label}"

        md = f"""#### [{status_indicator}] {test['test_id']}{test_label}

"""
        # Check for conversation format (memory test)
        if test.get("full_conversation"):
            md += "**Conversation:**\n"
            for msg in test["full_conversation"]:
                role = msg.get("role", "user")
                content = msg.get("content", "")
                md += f"- **{role}:** {content}\n"
            md += "\n"
        else:
            # Standard prompt/response format
            md += f"""**Prompt:**
```
{test.get('prompt', '')}
```

**Response:**
```
{test.get('response', '')}
```

"""

        md += f"**Reason:** {test.get('reason', '')}\n\n"

        if "elm_evaluation" in test:
            md += f"""**ELM Evaluation:**
> {test['elm_evaluation']}

"""
        return md
