"""
Base class for connectors / API clients

Connectors communicate with different backends by sending test prompts to them in a desired format, retrieving the outputs from the LLMs / AI models, and
sending original test prompts along with the output to an evaluative language model (ELM) for further vulnerability analysis.  

By abstracting the communication with different APIs to different connectors users can focus more on developing test cases and just pick a suitable API client
for their use case.
"""
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import List, Optional

logger = logging.getLogger(__name__)


@dataclass
class Message:
    """
    Represents a single message in a multi-turn conversation

    Attributes:
        role: The role of the message sender. "system", "user", or "assistant": https://platform.openai.com/docs/guides/text
        content: The text content of the message
    """
    role: str
    content: str


class BaseLMConnector(ABC):
    """
    A connector handles communication with a specific API / backend,
    abstracting the API usage for the framework.
    This allows test cases to be written only once and users are able to run them against different models with different configurations.

    Class methods:
    - single_turn(): Send a single prompt and get a response
    - multi_turn(): Send prompts, collect conversation history, and send conversation history back to the stateless API backend for history context.
    - single_turn_with_system_prompt(): Send a single prompt with a system prompt and get a response. 
        Used for providing contextual instructions to the evaluative language model.
    - health_check(): Verify the backend is available
    - list_models(): Get the list of available models on the backend. Used for 

    Class Attributes:
        name: Connector type identifier
        model: The specific model being used by the connertor (Defined in the configuration)
        api_key: Optional API key for authentication (Passed as a command line argument -apikey KEY)
    """

    name: str = ""
    model: str = ""
    api_key: Optional[str] = None

    @abstractmethod
    def single_turn(
        self,
        prompt: str,
        temperature: float = 1.0, #TODO: Set to 1.0 as default. Look more into this
        max_tokens: int = 512 #TODO: Look into this more
    ) -> str:
        """
        Send a single prompt to the LLM and collect a response

        Args:
            prompt: The test input prompt
            temperature: Controls the randomness and creativity of the model
            max_tokens: Maximum response length in tokens.

        Returns:
            The response generated by the target model

        Raises:
            RuntimeError: If the API call fails
        """
        pass

    def single_turn_with_system_prompt(
        self,
        prompt: str,
        system_prompt: str,
        temperature: float = 0.1, #Set to 0.1 as default to minimize randomness
        max_tokens: int = 512 #TODO: Look into this more
    ) -> str:
        """
        Send a single prompt to the LLM and collect a response

        Adds additional system prompt to the request, allowing to instruct the model's behavior.
        This method is intended to be used when sending the original test prompt and test output to
        a evaluative language model for analysing.

        Args:
            prompt: The prompt consisting of the original test prompt and the output of the target model.

            system_prompt: Instructions that define the model's behavior, role, or constraints. 
            Used to guide what the model should do and how to respond.

            temperature: Controls the randomness and creativity of the model. Set to low as default for deterministic responses.

            max_tokens: Maximum number of tokens in the generated response.

        Returns:
            The response generated by the model
        """
        combined = f"{system_prompt}\n\n{prompt}"
        return self.single_turn(combined, temperature, max_tokens)

    @abstractmethod
    def health_check(self) -> bool:
        """
        Check if the connector can reach destined backend and the target model is available.

        Returns:
            True if backend is reachable and the target model exists.

        Raises:
            ConnectionError: If the backend is not reachable.
            ValueError: If the model is not found.
        """
        pass

    def list_models(self) -> List[str]:
        """
        Helper function, used by health_check() to verify model availability.

        Returns:
            List of model names.

        Raises:
            Exception: If the backend is not reachable.
        """
        return []

    @abstractmethod
    def multi_turn(
        self,
        messages: List[Message],
        temperature: float = 1.0,
        max_tokens: int = 2048
    ) -> str:
        """
        Send multi-turn prompts, collect conversation history, and send conversation history back to the stateless API backend for history context.

        Unlike single_turn(), this method accepts the conversation history as a parameter,
        allowing the user to offer the often stateless model backends the conversation history from previous messages as context.

        With this implementation, the user is responsible for storing the conversation history and passing it forward to the target model.
       
        messages = [Message(role="user", content="Hello World")]
        response = connector.multi_turn(messages)
        messages.append(Message(role="assistant", content=response))

        Args:
            messages: List of Message objects representing the conversation history. Message objects contain 'role' and 'content' attributes for now.
            temperature: Controls the randomness and creativity of the model.
            max_tokens: Maximum response length in tokens.

        Returns:
            The model's response for the latest turn.

        Raises:
            RuntimeError: If the API call fails.
        """
        pass
