"""
Connector for OpenAI API communication.

Supports GPT-4, GPT-3.5-turbo, and other OpenAI chat completion models.
"""
import logging
from typing import List, Optional

from openai import OpenAI

from .base import BaseConnector, Message
from ...registry import connector_registry

logger = logging.getLogger(__name__)


@connector_registry.register("openai")
class OpenAIConnector(BaseConnector):
    """
    Connector for communicating with the OpenAI API.

    Used by tests for sending prompts to OpenAI models and collecting their responses.
    Supports both simple generation and generation with system prompts.

    Requires an API key, which can be passed via:
    - Constructor argument
    - Model config file (api_key field)
    - Command line (-apikey argument)
    """

    name = "openai"

    # Default models
    DEFAULT_MODEL = "gpt-4o-mini"

    def __init__(
        self,
        model: str = DEFAULT_MODEL,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None
    ):
        """
        Initialize the OpenAI connector.

        Args:
            model: Model name for generation (e.g., gpt-4o-mini, gpt-4o, gpt-3.5-turbo)
            api_key: OpenAI API key (required)
            base_url: Optional custom base URL (for Azure OpenAI or proxies)
        """
        if not api_key:
            raise ValueError("OpenAI connector requires an API key. Use -apikey argument or add api_key to model config.")

        self.model = model
        self.api_key = api_key
        self.base_url = base_url

        # Initialize OpenAI client
        client_kwargs = {"api_key": api_key}
        if base_url:
            client_kwargs["base_url"] = base_url

        self.client = OpenAI(**client_kwargs)

        logger.info(f"  OpenAI Connector Initialized")
        logger.info(f"  Model: {model}")
        if base_url:
            logger.info(f"  Base URL: {base_url}")
        logger.info(f"  API Key: {'*' * 8}...{api_key[-4:] if len(api_key) > 4 else '****'}")

    def single_turn(
        self,
        prompt: str,
        temperature: float = 1.0,
        max_tokens: int = 512
    ) -> str:
        """
        Send a single prompt to the LLM and collect a response.

        Args:
            prompt: The test input prompt.
            temperature: Controls the randomness and creativity of the model.
            max_tokens: Maximum response length in tokens.

        Returns:
            The response generated by the target model.

        Raises:
            RuntimeError: If the API call fails.
        """
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "user", "content": prompt}
                ],
                temperature=temperature,
                max_tokens=max_tokens
            )
            return response.choices[0].message.content or ""

        except Exception as e:
            logger.error(f"ERROR while generating response from OpenAI: {e}")
            raise RuntimeError(f"Failed to generate response from OpenAI: {e}")

    def single_turn_with_system_prompt(
        self,
        prompt: str,
        system_prompt: str,
        temperature: float = 0.1,
        max_tokens: int = 128
    ) -> str:
        """
        Send a single prompt to the LLM and collect a response.

        Adds additional system prompt to the request, allowing to instruct the model's behavior.
        This method is intended to be used when sending the original test prompt and test output to
        an evaluative language model for analysis.

        Args:
            prompt: The prompt consisting of the original test prompt and the output of the target model.

            system_prompt: Instructions that define the model's behavior, role, or constraints.
                Used to guide what the model should do and how to respond.

            temperature: Controls the randomness and creativity of the model.
                Set to low as default for deterministic responses.

            max_tokens: Maximum number of tokens in the generated response.

        Returns:
            The response generated by the model.

        Raises:
            RuntimeError: If the API call fails.
        """
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt}
                ],
                temperature=temperature,
                max_tokens=max_tokens
            )
            return response.choices[0].message.content or ""

        except Exception as e:
            logger.error(f"ERROR while generating response from OpenAI: {e}")
            raise RuntimeError(f"Failed to generate response from OpenAI: {e}")

    def health_check(self) -> bool:
        """
        Check if the connector can reach the OpenAI backend and the target model is available.

        Returns:
            True if backend is reachable and the target model exists.

        Raises:
            ConnectionError: If the backend is not reachable.
            ValueError: If the model is not found.
        """
        # Step 1: Check backend connectivity and API key validity
        try:
            model_ids = self.list_models()
        except Exception as e:
            base_url_info = f" at {self.base_url}" if self.base_url else ""
            raise ConnectionError(f"Cannot connect to OpenAI API{base_url_info}: {e}")

        # Step 2: Check if model exists
        logger.info(f"Available models found: {len(model_ids)} models")

        if self.model in model_ids:
            logger.info(f"Model '{self.model}' is available.")
            return True

        # Note: Some models (fine-tuned, newer) may not appear in list but still work
        logger.warning(
            f"Model '{self.model}' not found in available models list. "
            f"Proceeding anyway as some models may not be listed."
        )
        return True

    def list_models(self) -> List[str]:
        """
        Helper function, used by health_check() to verify model availability.

        Returns:
            List of model names.

        Raises:
            Exception: If the backend is not reachable.
        """
        models = self.client.models.list()
        return [m.id for m in models.data]

    def multi_turn(
        self,
        messages: List[Message],
        temperature: float = 1.0,
        max_tokens: int = 512
    ) -> str:
        """
        Send multi-turn prompts, collect conversation history, and send it back to the stateless API backend.

        Args:
            messages: List of Message objects representing the conversation history.
                Message objects contain 'role' and 'content' attributes.
            temperature: Controls the randomness and creativity of the model.
            max_tokens: Maximum response length in tokens.

        Returns:
            The model's response for the latest turn.

        Raises:
            RuntimeError: If the API call fails.
        """
        try:
            # Convert Message objects to OpenAI's expected format
            openai_messages = [
                {"role": msg.role, "content": msg.content}
                for msg in messages
            ]

            response = self.client.chat.completions.create(
                model=self.model,
                messages=openai_messages,
                temperature=temperature,
                max_tokens=max_tokens
            )
            return response.choices[0].message.content or ""

        except Exception as e:
            logger.error(f"ERROR during chat with OpenAI: {e}")
            raise RuntimeError(f"Failed to chat with OpenAI: {e}")
